Fixes certain errors with downloading on sourceforge
Tatsh/livecheck pull request #217
Opened 2024-10-14 15:17 UTC by inode64

2024-10-14 16:16 UTC, Tatsh commented
When does a JSON decode error happen? If SF is doing that it sounds like something to report.

2024-10-14 17:13 UTC, inode64 commented
I had left it as debug, because there are many times that sf does not implement access to that API in old applications
And I'm thinking of a strategy in case I can't find a version from sf

2024-10-16 17:55 UTC, Tatsh commented on livecheck/special/sourceforge.py
> +        if response.status_code == HTTPStatus.OK:
This line won't hit because of the above line `response.raise_for_status()` which raises an exception if the status is not 200.

2024-10-17 08:21 UTC, Tatsh requested changes

2024-10-17 08:21 UTC, Tatsh commented on livecheck/special/sourceforge.py
> +            filename = release['filename']
```suggestion
        if release and (filename := release.get('filename')):
```

2024-10-17 08:21 UTC, Tatsh commented on livecheck/special/sourceforge.py
> +            version_match = re.search(r'/(\d+(?:\.\d+)+)/', filename)
```suggestion
```

2024-10-17 08:21 UTC, Tatsh commented on livecheck/special/sourceforge.py
> +            if version_match:
```suggestion
            if version_match := re.search(r'/(\d+(?:\.\d+)+)/', filename):
```

2024-10-17 08:21 UTC, Tatsh commented on livecheck/special/sourceforge.py
> +            logger.debug(f"Could not extract filename o release: {url}")
```suggestion
            logger.debug(f"Could not extract filename or release: {url}")
```

2024-10-17 10:07 UTC, merged