Include nodejs and gomodule updaters
Tatsh/livecheck pull request #240
Opened 2024-11-15 07:47 UTC by inode64

Add 2 new modules to update the ebuilds

Along the way I have improved the logic of uploading to git

The digest is now generated automatically
I have changed so that updates can be multiple.
There are ebuilds that have both gomod and nodejs to process

I have added parameter control in the json file

It would be necessary to adjust the current updates so that they use the content of the main process, tell me if you see it correct and I will prepare it

2024-11-15 22:38 UTC, Tatsh commented
Regarding distribution archives for Go and Node.js, where are you putting these? It almost seems like livecheck should handle the uploading of these to somewhere. GitHub releases API would be an example place. But it should be sort of generic.

2024-11-15 22:38 UTC, Tatsh requested changes

2024-11-15 22:38 UTC, Tatsh commented on livecheck/special/utils.py
> +from loguru import logger
I want to get away from loguru.

```suggestion
import logging
logger = logging.getLogger(__name__)
```

Put `logger = ...` after `__all__`.

2024-11-15 22:38 UTC, Tatsh commented on livecheck/utils/portage.py
> +        return '/var/cache/distfiles'
```suggestion
    return '/var/cache/distfiles'
```

2024-11-15 22:38 UTC, Tatsh commented on livecheck/settings.py
> +                        f"Unknown \"type\" in {path}, only \"none\", \"regex\", and \"checksum\" are supported."
```suggestion
                        f'Unknown "type" in {path}, only "none", "regex", and "checksum" are supported.'
```

2024-11-15 22:38 UTC, Tatsh commented on livecheck/main.py
> +from .special.nodejs import update_nodejs_ebuild, remove_nodejs_url
Please sort the imports.

2024-11-15 22:38 UTC, Tatsh commented on livecheck/main.py
> +            # Write net ebuild content because it may be modified
Did you mean 'Write new ebuild content'?

2024-11-16 08:11 UTC, inode64 commented
> Regarding distribution archives for Go and Node.js, where are you putting these? It almost seems like livecheck should handle the uploading of these to somewhere. GitHub releases API would be an example place. But it should be sort of generic.
> 
> The reason I ask is because I currently have my own way of dealing with Node.js packages without having to make tarballs and for Go packages I still use the old EGO_SUM method. It is easier than trying to maintain the tarballs at the moment.

Yes, I will prepare that in a new pull request, because now I am doing it manually in my overlay
Now, if the compressed file is small, I left it in git
https://github.com/inode64/inode64-overlay/tree/main/dist
, and if not, I upload it to my web server

That's why I had thought about creating a hook to be able to perform these tasks automatically.

It was to avoid adding too much in the same pull request

2024-11-20 07:43 UTC, inode64 commented
Do you see this code correctly? Do I have to modify something else?

2024-11-20 09:06 UTC, Tatsh commented
There is a bug in this branch and in `master`. Ebuilds that have SHAs to update but not a different date according to Git have their ebuilds appear in the root of the project:

```
~/overlay $ ls -la *.ebuild
-rw-r--r-- 1 root root 682 2024-11-20 03:58:23 pymatting-1.1.12_p20241110-r1.ebuild
-rw-r--r-- 1 root root 468 2024-11-20 03:58:13 spirv-cross-20241113-r1.ebuild
-rw-r--r-- 1 root root 608 2024-11-20 03:58:29 vapoursynth-fsrcnn-ncnn-vulkan-20241112-r1.ebuild
```

The deletion of the old ebuild works but where the ebuild outputs is definitely wrong.

They should be in the `category/package_name` directory.

This is a scenario where there is a new commit in the same day or the SHA was incorrect.

```
2024-11-20 04:05:58.230 | DEBUG    | livecheck.main:get_props:101 - search_dir=/var/db/repos/tatsh
2024-11-20 04:05:58.260 | DEBUG    | livecheck.main:get_props:151 - Parsed path: /Sg4Dylan/vapoursynth-fsrcnn-ncnn-vulkan/archive/c9dad37dad64346afdff925fb409e6c6005b719a.tar.gz
2024-11-20 04:05:58.260 | DEBUG    | livecheck.main:main:423 - Fetching https://github.com/Sg4Dylan/vapoursynth-fsrcnn-ncnn-vulkan/commits/master.atom
2024-11-20 04:05:58.260 | DEBUG    | livecheck.main:main:431 - Adding Accept header for XML
2024-11-20 04:05:58.634 | DEBUG    | livecheck.main:do_main:292 - Using RE: "<id>tag:github.com,2008:Grit::Commit/([0-9a-f]{40})[0-9a-f]*</id>"
2024-11-20 04:05:58.634 | DEBUG    | livecheck.main:do_main:303 - Result count: 5
2024-11-20 04:05:58.634 | DEBUG    | livecheck.main:do_main:306 - re.findall() -> "0a721959116f6f86dbd13bda70a5fd6a883938f4"
2024-11-20 04:05:58.635 | DEBUG    | livecheck.main:do_main:323 - Attempted to fix top_hash date but it failed. Ignoring this error.
2024-11-20 04:05:58.635 | DEBUG    | livecheck.main:do_main:324 - top_hash = 0a721959116f6f86dbd13bda70a5fd6a883938f4
2024-11-20 04:05:58.635 | DEBUG    | livecheck.main:do_main:325 - Comparing current ebuild version c9dad37dad64346afdff925fb409e6c6005b719a with live version 0a721959116f6f86dbd13bda70a5fd6a883938f4
/var/db/repos/tatsh/media-video/vapoursynth-fsrcnn-ncnn-vulkan/vapoursynth-fsrcnn-ncnn-vulkan-20241112.ebuild -> vapoursynth-fsrcnn-ncnn-vulkan-20241112-r1.ebuild
```

The line showing the rename shows the bad target path.

2024-11-20 10:21 UTC, inode64 commented
Ok, nothing else I can do, I'll check it and solve it.

2024-11-24 12:46 UTC, inode64 commented
* Solve error when the hosts.yml file does not exist and without a manifest file for livechecks
* Add more types of variables to obtain the old sha 
* Remove variable prefixes in do_main, no longer used
* If the ebuild matches, use a new revision -r(+1)
* Unify the code to show the new ebuilds
* Moves the process of obtaining the regex within do_main, there may be code that does not use regex (jetbrains, pecl, sf, etc.) and thus eliminates the need to download the url
* Fix previous issues with packages
<pre>
2024-11-24 13:26:02.764 | INFO     | Processing dev-python/pymatting version 1.1.12_p20240409
dev-python/pymatting: 1.1.12_p20240409 (a073421a31afd0d53b7ff387ad2b361645b446be) -> 20241110 (afd2dec073cb08b8119300feec18c179a9d436f3)
2024-11-24 13:25:37.823 | INFO     | Processing media-video/vapoursynth-fsrcnn-ncnn-vulkan version 20200229
media-video/vapoursynth-fsrcnn-ncnn-vulkan: 20200229 (c9dad37dad64346afdff925fb409e6c6005b719a) -> 20241112 (0a721959116f6f86dbd13bda70a5fd6a883938f4)
2024-11-24 13:25:15.202 | INFO     | Processing dev-util/spirv-cross version 20240910
dev-util/spirv-cross: 20240910 (f84c1fbe3cbb69fa99e9115f658e52df0e95f1bf) -> 20241113 (9040e0d25dc545a6d725276bdbd0362791c81f14)
</pre>
I have checked with my repository and with the tatsh-overlay

2024-11-24 12:56 UTC, Tatsh commented
The bug I mentioned is still there.

```
2024-11-24 07:51:56.061 | DEBUG    | livecheck.main:get_props:101 - search_dir=/var/db/repos/tatsh
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:livecheck.utils.portage:Checking: /var/db/repos/tatsh == /var/db/repos/tatsh ?
2024-11-24 07:51:56.066 | DEBUG    | livecheck.main:get_props:151 - Parsed path: /Sg4Dylan/vapoursynth-fsrcnn-ncnn-vulkan/archive/c9dad37dad64346afdff925fb409e6c6005b719a.tar.gz
2024-11-24 07:51:56.066 | DEBUG    | livecheck.main:main:423 - Fetching https://github.com/Sg4Dylan/vapoursynth-fsrcnn-ncnn-vulkan/commits/master.atom
2024-11-24 07:51:56.066 | DEBUG    | livecheck.main:main:431 - Adding Accept header for XML
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): github.com:443
DEBUG:urllib3.connectionpool:https://github.com:443 "GET /Sg4Dylan/vapoursynth-fsrcnn-ncnn-vulkan/commits/master.atom HTTP/11" 200 4191
2024-11-24 07:51:56.278 | DEBUG    | livecheck.main:do_main:292 - Using RE: "<id>tag:github.com,2008:Grit::Commit/([0-9a-f]{40})[0-9a-f]*</id>"
2024-11-24 07:51:56.278 | DEBUG    | livecheck.main:do_main:303 - Result count: 5
2024-11-24 07:51:56.278 | DEBUG    | livecheck.main:do_main:306 - re.findall() -> "0a721959116f6f86dbd13bda70a5fd6a883938f4"
2024-11-24 07:51:56.279 | DEBUG    | livecheck.main:do_main:323 - Attempted to fix top_hash date but it failed. Ignoring this error.
2024-11-24 07:51:56.279 | DEBUG    | livecheck.main:do_main:324 - top_hash = 0a721959116f6f86dbd13bda70a5fd6a883938f4
2024-11-24 07:51:56.280 | DEBUG    | livecheck.main:do_main:325 - Comparing current ebuild version c9dad37dad64346afdff925fb409e6c6005b719a with live version 0a721959116f6f86dbd13bda70a5fd6a883938f4
/var/db/repos/tatsh/media-video/vapoursynth-fsrcnn-ncnn-vulkan/vapoursynth-fsrcnn-ncnn-vulkan-20241112.ebuild -> vapoursynth-fsrcnn-ncnn-vulkan-20241112-r1.ebuild
```

Please try to re-create this by creating the same ebuild as what is in my repository in your own repository or you can clone my repository (but it has to be in installed repositories).

https://github.com/Tatsh/tatsh-overlay/blob/master/media-video/vapoursynth-fsrcnn-ncnn-vulkan/vapoursynth-fsrcnn-ncnn-vulkan-20241112.ebuild

In your repo for testing:

```shell
mkdir -p media-video/vapoursynth-fsrcnn-ncnn-vulkan
wget 'https://raw.githubusercontent.com/Tatsh/tatsh-overlay/refs/heads/master/media-video/vapoursynth-fsrcnn-ncnn-vulkan/vapoursynth-fsrcnn-ncnn-vulkan-20241112.ebuild' -O media-video/vapoursynth-fsrcnn-ncnn-vulkan/vapoursynth-fsrcnn-ncnn-vulkan-20241112.ebuild'
ebuild media-video/vapoursynth-fsrcnn-ncnn-vulkan/vapoursynth-fsrcnn-ncnn-vulkan-20241112.ebuild manifest

# Run this branch of livecheck
livecheck -d -a vapoursynth-fsrcnn-ncnn-vulkan

# This should not output a file
ls *.ebuild
```

Please share the log.

2024-11-24 13:08 UTC, inode64 commented
<pre>
$ python -m livecheck -W /usr/portage/local/tatsh-overlay/media-video/vapoursynth-fsrcnn-ncnn-vulkan/ -p -d -a
!!! Found 2 make.conf files, using both '/etc/make.conf' and '/etc/portage/make.conf'
2024-11-24 14:06:40.536 | INFO     | livecheck.main:main:544 - search_dir=/usr/portage/local/tatsh-overlay/media-video/vapoursynth-fsrcnn-ncnn-vulkan repo_root=/usr/portage/local/tatsh-overlay repo_name=tatsh-overlay
DEBUG:asyncio:Using selector: EpollSelector
2024-11-24 14:06:40.539 | INFO     | livecheck.main:get_props:109 - Found 1 ebuilds
2024-11-24 14:06:40.539 | INFO     | livecheck.main:get_props:129 - Processing media-video/vapoursynth-fsrcnn-ncnn-vulkan version 20200229
2024-11-24 14:06:40.539 | DEBUG    | livecheck.main:get_props:165 - Parsed path: /Sg4Dylan/vapoursynth-fsrcnn-ncnn-vulkan/archive/c9dad37dad64346afdff925fb409e6c6005b719a.tar.gz
2024-11-24 14:06:40.540 | DEBUG    | livecheck.main:do_main:318 - Fetching https://github.com/Sg4Dylan/vapoursynth-fsrcnn-ncnn-vulkan/commits/master.atom
2024-11-24 14:06:40.540 | DEBUG    | livecheck.main:do_main:326 - Adding Accept header for XML
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): github.com:443
DEBUG:urllib3.connectionpool:https://github.com:443 "GET /Sg4Dylan/vapoursynth-fsrcnn-ncnn-vulkan/commits/master.atom HTTP/11" 200 4191
2024-11-24 14:06:40.867 | DEBUG    | livecheck.main:do_main:338 - Using RE: "<id>tag:github.com,2008:Grit::Commit/([0-9a-f]{40})[0-9a-f]*</id>"
2024-11-24 14:06:40.868 | DEBUG    | livecheck.main:do_main:350 - Result count: 5
2024-11-24 14:06:40.868 | DEBUG    | livecheck.main:do_main:354 - re.findall() -> "0a721959116f6f86dbd13bda70a5fd6a883938f4"
2024-11-24 14:06:40.868 | DEBUG    | livecheck.main:do_main:364 - Use updated date 20241112 for commit 0a721959116f6f86dbd13bda70a5fd6a883938f4
2024-11-24 14:06:40.869 | DEBUG    | livecheck.main:do_main:379 - Attempted to fix top_hash date but it failed. Ignoring this error.
2024-11-24 14:06:40.869 | DEBUG    | livecheck.main:do_main:380 - top_hash = 0a721959116f6f86dbd13bda70a5fd6a883938f4
2024-11-24 14:06:40.869 | DEBUG    | livecheck.main:do_main:388 - Comparing current ebuild version c9dad37dad64346afdff925fb409e6c6005b719a with live version 0a721959116f6f86dbd13bda70a5fd6a883938f4
2024-11-24 14:06:40.869 | DEBUG    | livecheck.main:do_main:393 - Updating ebuild /usr/portage/local/tatsh-overlay/media-video/vapoursynth-fsrcnn-ncnn-vulkan/vapoursynth-fsrcnn-ncnn-vulkan-20200229.ebuild to /usr/portage/local/tatsh-overlay/media-video/vapoursynth-fsrcnn-ncnn-vulkan/vapoursynth-fsrcnn-ncnn-vulkan-20241112.ebuild
media-video/vapoursynth-fsrcnn-ncnn-vulkan: 20200229 (c9dad37dad64346afdff925fb409e6c6005b719a) -> 20241112 (0a721959116f6f86dbd13bda70a5fd6a883938f4)
/usr/portage/local/tatsh-overlay/media-video/vapoursynth-fsrcnn-ncnn-vulkan/vapoursynth-fsrcnn-ncnn-vulkan-20200229.ebuild -> /usr/portage/local/tatsh-overlay/media-video/vapoursynth-fsrcnn-ncnn-vulkan/vapoursynth-fsrcnn-ncnn-vulkan-20241112.ebuild
>>> Downloading 'http://distfiles.gentoo.org/distfiles/04/vapoursynth-fsrcnn-ncnn-vulkan-20241112.tar.gz'
--2024-11-24 14:06:40--  http://distfiles.gentoo.org/distfiles/04/vapoursynth-fsrcnn-ncnn-vulkan-20241112.tar.gz
Resolving distfiles.gentoo.org (distfiles.gentoo.org)... 109.61.88.171, 109.61.88.175, 2a02:6ea0:c300::17, ...
Connecting to distfiles.gentoo.org (distfiles.gentoo.org)|109.61.88.171|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-11-24 14:06:41 ERROR 404: Not Found.

>>> Downloading 'https://github.com/Sg4Dylan/vapoursynth-fsrcnn-ncnn-vulkan/archive/0a721959116f6f86dbd13bda70a5fd6a883938f4.tar.gz'
--2024-11-24 14:06:41--  https://github.com/Sg4Dylan/vapoursynth-fsrcnn-ncnn-vulkan/archive/0a721959116f6f86dbd13bda70a5fd6a883938f4.tar.gz
Resolving github.com (github.com)... 140.82.121.3
Connecting to github.com (github.com)|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/Sg4Dylan/vapoursynth-fsrcnn-ncnn-vulkan/tar.gz/0a721959116f6f86dbd13bda70a5fd6a883938f4 [following]
--2024-11-24 14:06:42--  https://codeload.github.com/Sg4Dylan/vapoursynth-fsrcnn-ncnn-vulkan/tar.gz/0a721959116f6f86dbd13bda70a5fd6a883938f4
Resolving codeload.github.com (codeload.github.com)... 140.82.121.10
Connecting to codeload.github.com (codeload.github.com)|140.82.121.10|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘/usr/portage/distfiles/vapoursynth-fsrcnn-ncnn-vulkan-20241112.tar.gz.__download__’

/usr/portage/distfiles/vapoursynth-fsrcnn-ncnn-vulkan-20241112.tar.gz.     [ <=>                                                                                                                                                                       ]  79,69K  --.-KB/s    in 0,08s   

2024-11-24 14:06:42 (1010 KB/s) - ‘/usr/portage/distfiles/vapoursynth-fsrcnn-ncnn-vulkan-20241112.tar.gz.__download__’ saved [81607]

>>> Creating Manifest for /usr/portage/local/tatsh-overlay/media-video/vapoursynth-fsrcnn-ncnn-vulkan
</pre>

<pre>
$ ls /usr/portage/local/tatsh-overlay/media-video/vapoursynth-fsrcnn-ncnn-vulkan/
Manifest  files  metadata.xml  vapoursynth-fsrcnn-ncnn-vulkan-20241112.ebuild

</pre>

2024-11-24 13:42 UTC, inode64 commented
[tatsh.log](https://github.com/user-attachments/files/17893508/tatsh.log)

Include log

2024-11-24 14:31 UTC, inode64 commented
I have seen a problem, then I will upload the correction, after making the adjustments and tests

2024-11-24 15:25 UTC, Tatsh commented
Clean up your copy of my overlay and try this and send output:

```
python -m livecheck -W /usr/portage/local/tatsh-overlay/ -p -d -a vapoursynth-fsrcnn-ncnn-vulkan
ls /usr/portage/local/tatsh-overlay/*.ebuild
```

2024-11-24 20:16 UTC, Tatsh commented
Ignore the issue with -r1 files being placed in the root of the repo. That issue exists even in the last release. https://github.com/Tatsh/livecheck/issues/244

2024-11-24 20:17 UTC, Tatsh commented
Please either redo this PR or fix your branch so it does not need a merge. The project was renamed from `portage-livecheck` to `livecheck`.

2024-11-25 06:18 UTC, inode64 commented
now it seems to work
tonight I will redo the pull request

<pre>
2024-11-25 07:13:47.382 | INFO     | livecheck.main:get_props:109 - Found 1 ebuilds
2024-11-25 07:13:47.383 | INFO     | livecheck.main:get_props:129 - Processing media-video/vapoursynth-fsrcnn-ncnn-vulkan version 20241112
2024-11-25 07:13:47.383 | DEBUG    | livecheck.main:get_props:165 - Parsed path: /Sg4Dylan/vapoursynth-fsrcnn-ncnn-vulkan/archive/c9dad37dad64346afdff925fb409e6c6005b719a.tar.gz
2024-11-25 07:13:47.383 | DEBUG    | livecheck.main:do_main:324 - Fetching https://github.com/Sg4Dylan/vapoursynth-fsrcnn-ncnn-vulkan/commits/master.atom
2024-11-25 07:13:47.383 | DEBUG    | livecheck.main:do_main:332 - Adding Accept header for XML
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): github.com:443
DEBUG:urllib3.connectionpool:https://github.com:443 "GET /Sg4Dylan/vapoursynth-fsrcnn-ncnn-vulkan/commits/master.atom HTTP/11" 200 4191
2024-11-25 07:13:47.669 | DEBUG    | livecheck.main:do_main:344 - Using RE: "<id>tag:github.com,2008:Grit::Commit/([0-9a-f]{40})[0-9a-f]*</id>"
2024-11-25 07:13:47.669 | DEBUG    | livecheck.main:do_main:356 - Result count: 5
2024-11-25 07:13:47.669 | DEBUG    | livecheck.main:do_main:360 - re.findall() -> "0a721959116f6f86dbd13bda70a5fd6a883938f4"
2024-11-25 07:13:47.669 | DEBUG    | livecheck.main:do_main:370 - Use updated date 20241112 for commit 0a721959116f6f86dbd13bda70a5fd6a883938f4
2024-11-25 07:13:47.670 | DEBUG    | livecheck.main:do_main:385 - Attempted to fix top_hash date but it failed. Ignoring this error.
2024-11-25 07:13:47.670 | DEBUG    | livecheck.main:do_main:386 - top_hash = 0a721959116f6f86dbd13bda70a5fd6a883938f4
2024-11-25 07:13:47.670 | DEBUG    | livecheck.main:do_main:394 - Comparing current ebuild version c9dad37dad64346afdff925fb409e6c6005b719a with live version 0a721959116f6f86dbd13bda70a5fd6a883938f4
2024-11-25 07:13:47.670 | DEBUG    | livecheck.main:do_main:400 - Updating ebuild /usr/portage/local/tatsh-overlay/media-video/vapoursynth-fsrcnn-ncnn-vulkan/vapoursynth-fsrcnn-ncnn-vulkan-20241112.ebuild to /usr/portage/local/tatsh-overlay/media-video/vapoursynth-fsrcnn-ncnn-vulkan/vapoursynth-fsrcnn-ncnn-vulkan-20241112.ebuild
media-video/vapoursynth-fsrcnn-ncnn-vulkan: 20241112 (c9dad37dad64346afdff925fb409e6c6005b719a) -> 20241112-r1 (0a721959116f6f86dbd13bda70a5fd6a883938f4)
</pre>

2024-11-25 18:27 UTC, inode64 commented
Continue in #241

2024-11-25 18:27 UTC, closed without merging