include support for hooks
Tatsh/livecheck pull request #270
Opened 2024-12-23 15:43 UTC by inode64

Include help too

2024-12-25 11:12 UTC, Tatsh commented
I think it would be better to read hooks in order from a directory like other things do. You can use [platformdirs](https://platformdirs.readthedocs.io/en/latest/) and read from like: `sorted(listdir(platformdirs.user_config_path('xirvik', ensure_exists=True) / 'pre'))` (or `'post'`). Then for every single file (non-recursive), if the file is executable, run it.

This change would allow any amount of hooks to exist.

2024-12-25 11:13 UTC, Tatsh requested changes

2024-12-25 11:13 UTC, Tatsh commented on README.md
> +2. action: Action type, e.g., `post` or `pre`
```suggestion
- Action type, e.g. `post` or `pre`
```

2024-12-25 11:13 UTC, Tatsh commented on README.md
> +2. action: Action type, e.g., `post` or `pre`
```suggestion
- Action type, e.g. `post` or `pre`.
```

2024-12-25 11:13 UTC, Tatsh commented on README.md
> +9. hash_date: (Optional) Date associated with the hash.
```suggestion
- Category and package name, e.g. `dev-lang/php`.
- Previous version, e.g. `8.2.32-r2`.
- New version, e.g. `8.2.33`.
- SHA hash of the old version. Optional.
- SHA hash of the new version. Optional.
- Date associated with the hash. Optional.
```

2024-12-25 11:13 UTC, Tatsh commented on livecheck/main.py
> +            git: bool, hook: click.File | None) -> None:
```suggestion
            git: bool, hook: str | None) -> None:
```

2024-12-25 11:13 UTC, Tatsh commented on livecheck/main.py
> +                logger.error(f'Error running hook {hook.name}')
Shouldn't this exit here?

```suggestion
                click.echo(f'Error running hook {hook.name}.', err=True)
                raise click.Abort
```

2024-12-25 11:13 UTC, Tatsh commented on livecheck/main.py
> +                logger.error(f'Error running hook {hook.name}')
```suggestion
                click.echo(f'Error running hook {hook.name}.', err=True)
                raise click.Abort
```

2024-12-26 10:24 UTC, inode64 commented
I have included a directory of hooks so that it can be managed from github and included in the repository. Because if it is in the configuration it could not be included clearly in the overlay.
See: 
https://github.com/inode64/inode64-overlay/tree/main/scripts/hooks

2024-12-26 14:43 UTC, merged